// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgIqe_2f2Soz1Tny6lsBoKfpiaCsqAc-g',
    appId: '1:409984945180:web:5da8ec674a46a0e00a23d9',
    messagingSenderId: '409984945180',
    projectId: 'to-do-list-eba97',
    authDomain: 'to-do-list-eba97.firebaseapp.com',
    storageBucket: 'to-do-list-eba97.appspot.com',
    measurementId: 'G-Y9S98ZSQE1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0vIzs64Y23N7AdyRIiRzPXouVoZX4QSo',
    appId: '1:409984945180:android:b68a29a54647096b0a23d9',
    messagingSenderId: '409984945180',
    projectId: 'to-do-list-eba97',
    storageBucket: 'to-do-list-eba97.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_pxbDcWiQ2OuUL00ZgOkYSe2RtO1UO5I',
    appId: '1:409984945180:ios:e7454452e4794fba0a23d9',
    messagingSenderId: '409984945180',
    projectId: 'to-do-list-eba97',
    storageBucket: 'to-do-list-eba97.appspot.com',
    iosClientId: '409984945180-r0gehp61fvh02hj71nc8gkmcdq6h58pl.apps.googleusercontent.com',
    iosBundleId: 'com.example.seflStudyLab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_pxbDcWiQ2OuUL00ZgOkYSe2RtO1UO5I',
    appId: '1:409984945180:ios:e7454452e4794fba0a23d9',
    messagingSenderId: '409984945180',
    projectId: 'to-do-list-eba97',
    storageBucket: 'to-do-list-eba97.appspot.com',
    iosClientId: '409984945180-r0gehp61fvh02hj71nc8gkmcdq6h58pl.apps.googleusercontent.com',
    iosBundleId: 'com.example.seflStudyLab',
  );
}
